### ISSUE TITLE
Update usage example in readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.py#22]
- Change import from `from sentence_generator import SentenceGenerator` to `import ak-phase.py`
- Remove semicolons `;` from all line endings.

**Comment by rachelkam5** [comment]
Hi!  Can I give this a try?  This would be my first open source contribution.  Thanks!

**Comment by arshadkazmi42** [comment]
@rachelkam5 Go ahead and create a PR

**Comment by VivekShah1801** [comment]
@arshadkazmi42 merged

**Comment by arshadkazmi42** [comment]
You have merged it into your forked repo. You should create a PR in this repo, to get it merged here.
