### ISSUE TITLE
Add build badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.py#23]
Add build passing badge below the name.
Paste the below line

`[![Build Status](https://api.travis-ci.com/arshadkazmi42/ak-phrase.js.svg?branch=master)](https://api.travis-ci.com/arshadkazmi42/ak-phrase.js)
`

**Comment by meshack-mbuvi** [comment]
claim

**Comment by arshadkazmi42** [comment]
@meshack-mbuvi Awesome. Go for it

**Comment by arshadkazmi42** [comment]
PR merged #24
